apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-deployment
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: houssemdhahri93/emailservice
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
spec:
  selector:
    app: emailservice
  ports:
    - protocol: TCP
      port: 8080       
      targetPort: 8080 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: houssemdhahri93/paymentservice
          ports:
            - containerPort: 50051
          env:
          - name: PORT
            value: "50051"
          - name: DISABLE_PROFILER
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-service
spec:
  selector:
    app: paymentservice
  ports:
    - protocol: TCP
      port: 50051     
      targetPort: 50051 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice-deployment
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: houssemdhahri93/shippingservice
          ports:
            - containerPort: 50051
          env:
          - name: PORT
            value: "50051"
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice-service
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 50051     
      targetPort: 50051 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice-deployment
  labels:
    app: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: houssemdhahri93/adservice
          ports:
            - containerPort: 9555
          env:
          - name: PORT
            value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice-service
spec:
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555     
      targetPort: 9555 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice-deployment
  labels:
    app: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: currencyservice
          image: houssemdhahri93/currencyservice
          ports:
            - containerPort: 7000
          env:
          - name: PORT
            value: "7000"
          - name: DISABLE_PROFILER
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice-service
spec:
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 7000     
      targetPort: 7000 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice-deployment
  labels:
    app: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: houssemdhahri93/productcatalogservice
          ports:
            - containerPort: 3550
          env:
          - name: PORT
            value: "3550"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice-service
spec:
  selector:
    app: productcatalogservice
  ports:
    - protocol: TCP
      port: 3550     
      targetPort: 3550 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice-deployment
  labels:
    app: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: houssemdhahri93/recommendationservice
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice-service:3550"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice-service
spec:
  selector:
    app: recommendationservice
  ports:
    - protocol: TCP
      port: 8080     
      targetPort: 8080 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: houssemdhahri93/cartservice
          ports:
            - containerPort: 7070
          env:
          - name: PORT
            value: "7070"
          - name: redis_ADDR
            value: "redis-service:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice-service
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 7070     
      targetPort: 7070 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}        
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379     
      targetPort: 6379 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice-deployment
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: houssemdhahri93/checkoutservice
          ports:
            - containerPort: 5050
          env:
          - name: PORT
            value: "5050"
          - name: EMAIL_SERVICE_ADDR
            value: "emailservice-service:8080"
          - name: PAYMENT_SERVICE_ADDR
            value: "paymentservice-service:50051"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice-service:50051"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice-service:7000"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice-service:3550"
          - name: CART_SERVICE_ADDR
            value: "cartservice-service:7070"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice-service
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 5050     
      targetPort: 5050 
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: houssemdhahri93/frontend
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice-service:8080"
          - name: AD_SERVICE_ADDR
            value: "adservice-service:9555"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice-service:50051"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice-service:7000"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice-service:3550"
          - name: CART_SERVICE_ADDR
            value: "cartservice-service:7070"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice-service:5050"           
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080     
      targetPort: 8080
      nodePort: 30080 
  type: NodePort
